### ISSUE TITLE
ScalaJS CrossProject incompatible issue

### ISSUE THREAD

**Issue by ghost** [scoverage/sbt-scoverage#111] opened 2015-06-01 18:04 UTC
The ScalaJS `CrossProject` class "shares" code between JS/JVM builds by adding a path to the build. This causes the build to fail and in this case we only build fro JVM:

``` sbt
No source root found for

/home/travis/build/InTheNow/cats/state/jvm/../shared/src/main/scala/cats/state/State.scala (source roots: /home/travis/build/InTheNow/cats/state/shared/src/main/scala/)
```

ref https://travis-ci.org/InTheNow/cats/builds/64943666

CC @sjrd

**Comment by hawkw** [comment] 2015-07-03 18:35
:+1:

**Comment by alexarchambault** [comment] 2015-07-07 16:03
+1

**Comment by ngbinh** [comment] 2015-07-07 16:04
:100:

**Comment by alexarchambault** [comment] 2015-07-07 16:06
Stumbled upon it here too:
https://github.com/fthomas/refined/blob/master/build.sbt#L190-L191

**Comment by hawkw** [comment] 2015-07-07 20:26
I am fairly sure that this issue has actually been fixed in Scala.js; just make sure you're using Scala.js v0.6.4 rather than v0.6.3 (which I believe is still mentioned in some of the Scala.js sample material).

**Comment by alexarchambault** [comment] 2015-07-07 20:31
I was using scalajs 0.6.3 indeed (I switched to 0.6.4 a few minutes ago).

**Comment by alexarchambault** [comment] 2015-07-07 20:47
This is better with scalajs 0.6.4 (and SBT 0.13.8 / scala 2.11.7, I can get a report for JVM projects at least). @hawkw Thanks.

**Comment by fthomas** [comment] 2015-07-07 20:48
I can confirm that this seems to be working for me too with Scala.js 0.6.4.

**Comment by ckipp01** [comment] 2021-04-28 14:30
This seems to have been fixed. If there is still an issue here, please do comment back.

**Closed by ckipp01** 2021-04-28 14:30 UTC
Labels: bug
