### ISSUE TITLE
Dependency issue with play framework

### ISSUE THREAD

**Issue by mickaelmagniez** [scoverage/sbt-scoverage#469] opened 2022-10-11 09:33 UTC
Hi

I have an issue while trying to use version 2.0.5 of scoverage on a "bare" play framework project : 

First i create a play project from seed with 
```
sbt new playframework/play-scala-seed.g8
```

And then i add `scoverage` to plugins, so i have 
```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.17")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.5")
```

```scala
name := """play-scala-seed"""
organization := "com.example"
version := "1.0-SNAPSHOT"
scalaVersion := "2.13.8"
lazy val root = (project in file(".")).enablePlugins(PlayScala)
libraryDependencies += guice
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "5.0.0" % Test
```

And then trying to run, i have 
```bash
$ sbt coverage

[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error]         * org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0, 1.1.1, 1.0.6}
[error]             +- org.scoverage:scalac-scoverage-reporter_2.12:2.0.7 (depends on 2.1.0)
[error]             +- org.scala-lang:scala-compiler:2.12.16              (depends on 1.0.6)
[error]             +- com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.1.1)
[error]             +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
```

It works well with scoverage 1.9, but upgrade to 2.0 leads to this problem.

Thank you for your help

Best regards

**Comment by ckipp01** [comment] 2022-10-11 09:52
Duplicate of #463 #461 

You can see more context and a fix in https://github.com/scala/bug/issues/12632.

**Closed by ckipp01** 2022-10-11 09:52 UTC
