### ISSUE TITLE
Version 1.3.0 referenced in readme but not actually available

### ISSUE THREAD

**Issue by holograph** [scoverage/sbt-scoverage#125] opened 2015-07-23 07:47 UTC
Although the readme states the latest version is 1.3.0, it's nowhere to be found ([BinTray](https://dl.bintray.com/sbt/sbt-plugin-releases/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/) lists latest version at 1.2.0, and [Central](http://search.maven.org/#search|ga|1|g%3Aorg.scoverage) doesn't appear to have _any_ releases).

**Comment by sksamuel** [comment] 2015-07-23 09:59
It's available in my repo

https://dl.bintray.com/sksamuel/sbt-plugins/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/

I think we just have to wait until it mirrors into the official one:

https://dl.bintray.com/sbt/sbt-plugin-releases/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/

**Comment by Kevin-Lee** [comment] 2015-07-24 15:23
@holograph If you want to use it right now just like me, as you know, you can set `plugins.sbt` with @sksamuel's repository like this.

```scala
resolvers += Resolver.url("sbt-scoverage repo", url("https://dl.bintray.com/sksamuel/sbt-plugins"))(Resolver.ivyStylePatterns)

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.0")
```

Unfortunately, the following way doesn't work. 
```scala
resolvers += "repo name" at "repo URL"
```

**Comment by sksamuel** [comment] 2015-07-24 15:25
I don't know why its not linking. I've sent a message to bintray to see why its not syncing.

**Comment by Kevin-Lee** [comment] 2015-07-24 15:38
That is not the only problem. [It doesn't seem to work](https://github.com/scoverage/sbt-coveralls/issues/57#issuecomment-124559188). I'm not sure if it's `sbt-scoverage`'s issue or `sbt-coveralls`'s so couldn't create an issue ticket. If you let me know, I'll create the ticket.

**Comment by aborg0** [comment] 2015-07-26 08:14
@sksamuel about not syncing: probably @jsuereth has some idea according to his comment on the sbt issue.

**Comment by sksamuel** [comment] 2015-07-28 07:05
I've updated the readme and will contact Josh, thanks.

**Comment by hrj** [comment] 2015-07-28 07:37
I suggest keeping the issue open until the problem is resolved. Or is there another issue which I can subscribe to? Thanks!

**Comment by sksamuel** [comment] 2015-07-28 07:38
Ok reopened.

**Comment by diwalak** [comment] 2015-08-11 07:09
Any progress here.
Not sure why this has not transferred even after a couple of weeks.

**Comment by sksamuel** [comment] 2015-08-11 10:14
The readme was updated to add details of the resolver to add. I can't get
bintray to sync.

**Comment by holograph** [comment] 2015-08-11 12:12
@sksamuel I can put you in touch with Jfrog if you think that'll help. Send me a paragraph or so on what isn't working to (tomer at tomergabel dot com) and I'll see what I can do...

**Comment by hseeberger** [comment] 2015-08-13 12:19
@jsuereth, any comments?

**Comment by sksamuel** [comment] 2015-08-13 13:26
I have a 1.3.1 release to do so could try again and hope for the best.

**Comment by ngbinh** [comment] 2015-08-14 09:54
I see `1.3.0` but not `1.3.1` https://dl.bintray.com/sksamuel/sbt-plugins/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/

**Comment by lloydmeta** [comment] 2015-08-17 01:32
^ :+1: would be nice to have a 1.3.1 release available.

**Comment by scosenza** [comment] 2015-08-17 03:59
+1

On Sunday, August 16, 2015, Lloyd <notifications@github.com> wrote:

> ^ [image: :+1:] would be nice to have a 1.3.1 release available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scoverage/sbt-scoverage/issues/125#issuecomment-131649150>
> .
>


-- 
-Steve

Sent from Gmail Mobile

**Comment by sksamuel** [comment] 2015-08-17 04:01
@ngbinh @lloydmeta  @scosenza  1.3.1 is available in my bintray now
https://dl.bintray.com/sksamuel/sbt-plugins/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/

**Comment by ngbinh** [comment] 2015-08-17 04:19
@sksamuel thanks

**Comment by lloydmeta** [comment] 2015-08-17 05:29
@sksamuel thanks :)

**Comment by seanrand57** [comment] 2016-01-06 19:54
@sksamuel I'm a little late to the party here but I'm trying to use version 1.3.1 using the following in my SBT plugins but it is downloading 1.1.1 in my ivy cache... any ideas?

resolvers += Resolver.url("sbt-scoverage", url("https://dl.bintray.com/sksamuel/sbt-plugins"))(Resolver.ivyStylePatterns)

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.1")

Cheers

**Comment by sksamuel** [comment] 2016-01-06 22:26
You need to get it from maven central, and not the bintray location (as
that's old now).

**Comment by seanrand57** [comment] 2016-01-06 22:57
Thanks Stephen appreciate it

**Comment by nemoo** [comment] 2019-06-21 11:45
Any progress here? I am trying to use version 1.6.0 and want to pull it from the standard dl.bintray.com/sbt/sbt-plugin-releases repository.

**Comment by gslowikowski** [comment] 2019-06-21 12:08
Everything is in Maven central repo - http://repo1.maven.org/maven2/org/scoverage/

**Comment by ckipp01** [comment] 2021-04-28 14:15
Seeing that this seems to be solved and we are quite further in the releases now, I'm going to close this.

**Closed by ckipp01** 2021-04-28 14:15 UTC
