### ISSUE TITLE
No source root found for `.../modules/core/shared/src/main/scala-3/io/circe/Derivation.scala`

### ISSUE THREAD

**Issue by nikololiahim** [scoverage/sbt-scoverage#444] opened 2022-07-04 12:04 UTC
I don't know if this affects only `circe` or any code that uses the `derives` keyword.
### To reproduce:
1. Clone this [gist](https://gist.github.com/nikololiahim/50ed09c1c501dcad72e6c255b9394a29).
2. (idk if this affects anything) move `User.scala` to `src/main/scala` folder and `UserTest.scala` to `src/test/scala` folder.
3. Run `sbt clean coverage test coverageReport`

### Problem
The command fails with:
```
[error] java.lang.RuntimeException: No source root found for '/home/nikololiahim/scala/scoverage-bug/modules/core/shared/src/main/scala-3/io/circe/Derivation.scala' (source roots: '/home/nikololiahim/scala/scoverage-bug/src/main/scala/')
[error]         at scoverage.reporter.BaseReportWriter.relativeSource(BaseReportWriter.scala:35)
[error]         at scoverage.reporter.BaseReportWriter.relativeSource(BaseReportWriter.scala:23)
[error]         at scoverage.reporter.ScoverageHtmlWriter.classRow(ScoverageHtmlWriter.scala:249)
[error]         at scoverage.reporter.ScoverageHtmlWriter.$anonfun$classesTable$2(ScoverageHtmlWriter.scala:239)
[error]         at scala.collection.immutable.List.map(List.scala:293)
[error]         at scoverage.reporter.ScoverageHtmlWriter.classesTable(ScoverageHtmlWriter.scala:239)
[error]         at scoverage.reporter.ScoverageHtmlWriter.overview(ScoverageHtmlWriter.scala:460)
[error]         at scoverage.reporter.ScoverageHtmlWriter.write(ScoverageHtmlWriter.scala:65)
[error]         at scoverage.ScoverageSbtPlugin$.writeReports(ScoverageSbtPlugin.scala:324)
[error]         at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1(ScoverageSbtPlugin.scala:220)
[error]         at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1$adapted(ScoverageSbtPlugin.scala:195)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (coverageReport) No source root found for '/home/nikololiahim/scala/scoverage-bug/modules/core/shared/src/main/scala-3/io/circe/Derivation.scala' (source roots: '/home/nikololiahim/scala/scoverage-bug/src/main/scala/')
```

**Comment by nikololiahim** [comment] 2022-07-04 12:53
@ckipp01 Just tried with 2.13.8, seems to work correctly. I had to rewrite the code a bit:
`User.scala`
```scala
import io.circe._
import io.circe.generic.semiauto._

case class User(name: String, address: Address)
case class Address(country: String, city: String)

object User {
  implicit val userDecoder: Codec[User] = deriveCodec
  implicit val addrDecoder: Codec[Address] = deriveCodec
  def fromString(s: String): Option[User] = {
    s.split(",[ ]?") match {
      case Array(name, country, city) =>
        Some(User(name, Address(country, city)))
      case _ => None
    }
  }
}
```

And also add
```scala
"io.circe" %% "circe-generic-extras" % "0.14.2",
```
to `build.sbt`.

Seems like the problem is indeed tied to the `derives` keyword.

**Comment by ckipp01** [comment] 2022-07-04 12:57
Gotcha, since this works for 2.13, are you then able to create an issue for this over at https://github.com/lampepfl/dotty/issues since I believe it will actually need to be fixed over there.

**Comment by nikololiahim** [comment] 2022-07-04 13:24
@ckipp01 Should I copy it as is or should I reword it somehow?

**Comment by ckipp01** [comment] 2022-07-04 13:39
You can just copy and just ensure that you have a minimal reproduction.

**Comment by nikololiahim** [comment] 2022-07-04 14:39
seems like it was already reported: https://github.com/lampepfl/dotty/issues/15490

**Comment by ckipp01** [comment] 2022-07-04 14:41
> seems like it was already reported: https://github.com/lampepfl/dotty/issues/15490

Ah, perfect. I totally missed that.

**Comment by rochala** [comment] 2022-07-04 19:40
@ckipp01 I checked this issue on dotty side and the generation looks to be working as intended. I closed the issue as `scoverage.coverage` contained derived methods and whole test project passed and compiled under `-coverage-out:.` flag. The problem is also not connected to this issue https://github.com/lampepfl/dotty/issues/15490 as it is about coverage data generated from macros which led to misleading data.

**Comment by ruippeixotog** [comment] 2022-09-22 04:55
This issue seems to be preventing PureConfig from enabling coverage on Scala 3 (https://github.com/pureconfig/pureconfig/pull/1387).

**Comment by z4f1r0v** [comment] 2022-10-24 08:07
Same thing with Scala `3.2.0` and circeVersion `0.15.0-M1`

**Comment by ckipp01** [comment] 2022-10-24 08:27
Note that this is probably the same issue as in #458 and I believe should be fixed by the work in https://github.com/lampepfl/dotty/pull/16235.

**Comment by TheElectronWill** [comment] 2022-10-24 09:09
IMO, fixing the coverage instrumentation is good but the report writer of scoverage should be able to ignore missing sources :thinking: Design for failure :)

**Comment by ckipp01** [comment] 2022-10-24 09:33
> IMO, fixing the coverage instrumentation is good but the report writer of scoverage should be able to ignore missing sources

But then how else would we know the instrumentation is broken! Jokes aside, it's probably a good idea to loudly warn the user in this situation but gracefully continue. As you said it'd require some small changes in https://github.com/scoverage/scalac-scoverage-plugin, which I'd be happy to review.

**Comment by z4f1r0v** [comment] 2022-10-31 08:45
Apologies for being a pest but what is the state now? It looks like https://github.com/lampepfl/dotty/pull/16235 is merge (thank you @TheElectronWill). I see that dotty is at 3.2.1-RC4. Will that changset make it in 3.2.1? 
If that is the case, from what I get from this thread, a subsequent change needs to be made to https://github.com/scoverage/scalac-scoverage-plugin? Is that what is supposed to happen or am I misunderstanding?

**Comment by ckipp01** [comment] 2022-10-31 08:51
> Will that changset make it in 3.2.1?

3.2.1 is actually released already, just not announced as the other parts of the ecosystem need to catch up. https://github.com/lampepfl/dotty/releases/tag/untagged-6fa1a15db952f2cb4a28

> If that is the case, from what I get from this thread, a subsequent change needs to be made to https://github.com/scoverage/scalac-scoverage-plugin? Is that what is supposed to happen or am I misunderstanding?

Nope, this will just be fixed when the coverage output from the compiler is fixed. There are some changes we _can_ make to maybe hand this type of situation a bit better though, and I'm open to review those changes.

**Comment by z4f1r0v** [comment] 2022-11-20 22:00
Scala `3.2.2-RC1` solved this for me.

**Closed** 2022-11-21 08:33 UTC
Labels: scala 3

**Comment by godenji** [comment] 2023-06-19 14:24
Getting the "No source root found for ..." error on `scala-3.3.1-RC1`, although in my case it's not related to the `derives` keyword.

Could be a cross project issue? The listed source roots are correct, but where `scoverage` thinks the missing source file is is not correct -- it's looking in the top-level project (where sbt console session is initiated) instead of correct source root directory).

No idea why this is happening, but it makes `scoverage` in a multi-project build unusable at the moment.
